config/routes.rb
CornerOffice::Application.routes.draw do
  resource :account, :controller => :users, :only => [:new, :create, :edit, :update] do
    resource :password, :only => [:edit]
  end

  match "/login" => "sessions#new", :as => "login"

  get "/authorize" => "tokens#create", :as => "authorize"

  resource :session, :only => [:new, :create, :destroy]
  resource :token, :only => [:new]
  resources :deals, :only => [:show, :edit, :update]
  resource :password, :only => [:new, :create]

  root :to => "deals#index"

  # need this because Rails `rescue_from` doesn't catch ActionController::RoutingError
  unless Rails.env.development?
    match '*path',  :to => 'application#render_404'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include SimplestAuth::Model
  include PasswordResettable

  authenticate_by :email

  has_many :tokens, :order => "created_at DESC", :after_add => :set_default_site

  attr_accessible :password, :password_confirmation, :email, :first_name, :last_name, :site

  validates :first_name, :last_name, :email, :presence => true
  validates :email, :email => true, :uniqueness => true

  validates :password, :length => {:minimum => 8}, :if => :password_required?
  validates :password, :presence => true, :on => :create
  validates :password_confirmation, :presence => true, :on => :create
  validates :password, :confirmation => true

  def name
    "#{first_name} #{last_name}"
  end

  def token
    tokens.first
  end

  def highrise_sites
    @highrise_sites ||= authorization.highrise_sites if authorization
  end

  def unauthorized_token?
    token && !authorization
  end

  def set_default_site
    if highrise_sites && highrise_sites.count == 1
      update_attributes(:site => highrise_sites.first[1])
    end
  end

  private

  def authorization
    @authorization ||= get_authorization
  end

  def get_authorization
    if token.present?
      Highrise::Base.oauth_token = token.secret
      Highrise::Authorization.retrieve
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_authentication, :only => [:edit, :update]

  helper_method :highrise_sites

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      self.current_user = @user
      redirect_to edit_account_path, :notice => t("user.create.success")
    else
      flash.now[:error] = t("user.create.error")
      render "new"
    end
  end

  def edit
  end

  def update
    if current_user.update_attributes(params[:user])
      redirect_to edit_account_path, :notice => t("user.update.success")
    else
      flash.now[:error] = t("user.update.error")
      render "edit"
    end
  end

  private

  def highrise_sites
    @highrise_sites ||= current_user.try(:highrise_sites)
  end
end

app/views/users/_form_fields.html.erb
<%= f.input :first_name %>
<%= f.input :last_name %>
<%= f.input :email %>
<%= f.input :site, :label => "Highrise Site", :collection => highrise_sites if highrise_sites %>
<%= f.input :password %>
<%= f.input :password_confirmation %>

app/views/users/edit.html.erb
<h2>Edit your account</h2>

<%- if current_user.unauthorized_token? -%>
  <div class="alert alert-error">Your Highrise authorization has expired. Please relink your account.</div>
<%- end -%>

<%- if current_user.unauthorized_token? -%>
  <%= link_to "Relink Your Highrise Account", new_token_path, :id => "authorize_highrise", :class => "btn btn-primary" %>
<%- elsif current_user.token.present? -%>
  <%= link_to "Refresh Highrise Authorization", new_token_path, :id => "authorize_highrise", :class => "btn" %>
<%- else -%>
  <%= link_to "Link Your Highrise Account", new_token_path, :id => "authorize_highrise", :class => "btn btn-primary" %>
<%- end -%>

<%= simple_form_for current_user, :url => account_path, :method => :put do |f| %>
  <%= render "form_fields", :f => f %>
  <%= f.button :submit, :value => "Submit" %>
<% end %>

app/views/users/new.html.erb
<h2>Create an account</h2>
<%= simple_form_for @user, :url => account_path do |f| %>
  <%= render "form_fields", :f => f %>
  <%= f.button :submit, :value => "Submit" %>
<% end %>