config/routes.rb
CornerOffice::Application.routes.draw do
  resource :account, :controller => :users, :only => [:new, :create, :edit, :update] do
    resource :password, :only => [:edit]
  end

  match "/login" => "sessions#new", :as => "login"

  get "/authorize" => "tokens#create", :as => "authorize"

  resource :session, :only => [:new, :create, :destroy]
  resource :token, :only => [:new]
  resources :deals, :only => [:show, :edit, :update]
  resource :password, :only => [:new, :create]

  root :to => "deals#index"

  # need this because Rails `rescue_from` doesn't catch ActionController::RoutingError
  unless Rails.env.development?
    match '*path',  :to => 'application#render_404'
  end
end

app/models/deal.rb
class Deal < Highrise::Deal
  include ReadOnlyResource

  def self.with_preloaded_deal_data(deals)
    deals.tap do |deals|
      DealDataPreloader.new(deals).preload
    end
  end

  def self.filter(filter, deals)
    filter_method = "#{filter}_filter"
    send(filter_method, deals) if respond_to?(filter_method)
  end

  def deal_data=(deal_data)
    @deal_data = deal_data || DealData.new(:deal_id => self.id)
  end

  def deal_data
    @deal_data ||= find_or_build_deal_data
  end

  def update_deal_data(attributes)
    deal_data.update_attributes(attributes.fetch("deal_data", {}))
  end

  def daily_budget
    deal_data.daily_budget(price || 0)
  end

  delegate :start_date, :end_date, :date_range, :probability, :average_rate,
    :to => :deal_data, :allow_nil => true

  private

  def self.missing_data_filter(deals)
    [].tap do |deals_missing_data|
      deals.each do |deal|
        unless deal.start_date && deal.end_date && deal.price
          deals_missing_data.push(deal)
        end
      end
    end
  end

  def find_or_build_deal_data
    DealData.where(:deal_id => self.id).first_or_initialize
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  helper_method :deal, :deals, :deals_missing_data

  before_filter :require_authentication
  before_filter :require_oauth_token
  before_filter :require_highrise_site

  def index
    @chart = Visualization::DealsByMonthChart.new(deals)
  end

  def show
    @chart = Visualization::DealsByMonthChart.new([deal])
  end

  def edit
  end

  def update
    if deal.update_deal_data(params[:deal])
      redirect_to deal_path(deal), :notice => t("deal.update.success")
    else
      flash.now[:error] = t("deal.update.error")
      render "edit"
    end
  end

  private

  def require_oauth_token
    if current_user.token.present?
      Highrise::Base.oauth_token = current_user.token.secret
    else
      redirect_to edit_account_path, :alert => t("token.required")
    end
  end

  def require_highrise_site
    if current_user.site?
      Highrise::Base.site = current_user.site
    else
      redirect_to edit_account_path, :alert => t("highrise.site.required")
    end
  end

  def deal
    @deal ||= Deal.find(params[:id])
  end

  def deals
    @deals ||= Deal.with_preloaded_deal_data(all_deals) - deals_missing_data
  end

  def all_deals
    @all_deals ||= Deal.find(:all, :params => { :status => "pending" })
  end

  def deals_missing_data
    @deals_missing_data ||= Deal.filter(:missing_data, all_deals)
  end
end

app/views/deals/_chart.html.erb
<div id="deal-visualization"></div>

<script type="text/javascript">
  <%= render :partial => "google_chart", :formats => [:js], :locals => { :chart => chart, :chart_options => chart_options } %>
</script>

app/views/deals/_google_chart.js.erb
function drawVisualization() {
  var dataTable = google.visualization.arrayToDataTable(<%= raw(chart.to_a.to_json) %>);
  var wrapper = new google.visualization.ColumnChart(document.getElementById("deal-visualization"));

  google.visualization.events.addListener(wrapper, "ready", onReady);

  wrapper.draw(
    dataTable,
    {
      title:     "<%= chart_options[:title] %>",
      isStacked: true,
      width:     920,
      height:    500,
      hAxis:     { title: "Month" },
      vAxis:     { format: "$#,###" },
      legend:    { position: "<%= chart_options[:legend] %>" }
    }
  );

  function onReady() {
    google.visualization.events.addListener(wrapper, "onmouseover", overHandler);
    google.visualization.events.addListener(wrapper, "onmouseout", outHandler);
  }

  function overHandler(e) {
    wrapper.setSelection([{"row": null, "column": e.column}]);
  }

  function outHandler(e) {
    wrapper.setSelection([{"row": null, "column": null}]);
  }
}

google.setOnLoadCallback(drawVisualization);

app/views/deals/_table.html.erb
<%- if deals.any? -%>
  <table class="<%= klass %> table tablesorter">
    <thead>
      <tr>
        <th>Name</th>
        <th>Budget</th>
        <th>Win Probability</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Average Rate</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% deals.each do |d| %>
        <tr>
          <td><%= link_to d.name, deal_path(d) %></td>
          <td><%= number_to_currency(d.price, :precision => 0) %></td>
          <td style="background-color: hsl(<%= d.deal_data.probability %>,50%, 92%);">
            <%= number_to_percentage(d.deal_data.probability, :precision => 0) %>
          </td>
          <td><%= d.deal_data.start_date %></td>
          <td><%= d.deal_data.end_date %></td>
          <td><%= number_to_currency(d.deal_data.average_rate, :precision => 0) %></td>
          <td><%= link_to "Edit", edit_deal_path(d), :class => 'btn btn-small' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<%- else -%>
  <div class="alert">Nothing to see here.</div>
<%- end -%>

app/views/deals/edit.html.erb
<%= link_to "Back to Deals", root_path %>
<h1>Editing <%= deal.name %></h1>
<%= simple_form_for deal do |f| %>
  <%= f.simple_fields_for deal.deal_data do |dd| %>
    <%= dd.input :start_date, :as => :date %>
    <%= dd.input :end_date, :as => :date, :default => 1.day.from_now %>
    <%= dd.input :probability, :label => "Win Probability" %>
    <%= dd.input :average_rate %>
  <% end %>
  <%= f.button :submit %>
  <%= link_to "Cancel", @deal%>
<% end %>

app/views/deals/index.html.erb
<h2>Deals</h2>
<%= render "table", :deals => deals, :klass => "deals" %>

<%= render :partial => "chart",
           :locals  => {
              :chart         => @chart,
              :chart_options => {
                  :title  => "Projects by Month (Budget/Project Duration)",
                  :legend => "right" }
              }
%>

<%- if deals_missing_data.any? -%>
  <h3>Deals Missing Data</h3>
  <%= render "table", :deals => deals_missing_data, :klass => "deals-missing-data" %>
<%- end -%>

app/views/deals/show.html.erb
<%= link_to "Back to Deals", root_path %>
<h2><%= deal.name %></h2>
<%= link_to "Edit", edit_deal_path(deal), :class => 'btn' %>
<%= link_to "View on Highrise", url_for("#{Highrise::Base.site}deals/#{deal.id}"),
      :target => :blank, :class => 'btn' %>

<p>
  <strong>Budget:</strong>
  <%= number_to_currency(deal.price, :precision => 0) %>
</p>

<p>
  <strong>Expected Start Date:</strong>
  <%= deal.start_date %>
</p>

<p>
  <strong>Expected End Date:</strong>
  <%= deal.end_date %>
</p>

<p>
  <strong>Win Probability:</strong>
  <%= number_to_percentage(deal.probability, :precision => 0) %>
</p>

<p>
  <strong>Average Rate:</strong>
  <%= number_to_currency(deal.average_rate, :precision => 0) %>
</p>

<%= render :partial => "chart",
           :locals  => {
              :chart         => @chart,
              :chart_options => {
                  :title  => "Project Timeline",
                  :legend => "none" }
              }
%>