config/routes.rb
CornerOffice::Application.routes.draw do
  resource :account, :controller => :users, :only => [:new, :create, :edit, :update] do
    resource :password, :only => [:edit]
  end

  match "/login" => "sessions#new", :as => "login"

  get "/authorize" => "tokens#create", :as => "authorize"

  resource :session, :only => [:new, :create, :destroy]
  resource :token, :only => [:new]
  resources :deals, :only => [:show, :edit, :update]
  resource :password, :only => [:new, :create]

  root :to => "deals#index"

  # need this because Rails `rescue_from` doesn't catch ActionController::RoutingError
  unless Rails.env.development?
    match '*path',  :to => 'application#render_404'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CornerOffice</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" ></script>
  <script type="text/javascript" src="//cdn.jsdelivr.net/tablesorter/2.0.5b/jquery.tablesorter.js"></script>
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
  <script type="text/javascript">
    google.load('visualization', '1', {packages: ['corechart']});
  </script>
</head>
<body>
  <div class="container">
    <div class="navbar">
      <div class="navbar-inner">
        <%= link_to "Corner Office", root_url, :class => 'brand' %>
        <ul class="nav pull-right">
          <% if logged_in? %>
            <li><%= link_to "Deals", root_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                You
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit Account", edit_account_path %></li>
                <li><%= link_to "Logout", session_path, :method => :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Login", login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>

    <%- flash.to_hash.values_at(:error, :notice, :alert).select(&:present?).each do |value| -%>
      <div class="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= value %>
      </div>
    <%- end -%>

    <%= yield %>

  </div>
</body>
</html>